[build]
  base = "."
  publish = "dist"
  command = "npm run build"
[functions]
  node_bundler = "esbuild"
[[redirects]]
  from = "/_astro/*"
  to = "/_astro/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/favicon.svg"
  to = "/favicon.svg"
  status = 200
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true